version: "3.9"

services:

    # ML app
    mlapp:
        build:
            context: ./src
            dockerfile: Dockerfile
        volumes:
            - ./src:/app/src
        depends_on:
            celery-worker:
                condition: service_started
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        ports:
            - 8000:8000

    # Celery worker
    celery-worker:
        build:
            context: ./src
            dockerfile: celery/Dockerfile
        volumes:
            - ./src:/app/src
            - ./.logs:/logs
        depends_on:
            - rabbitmq
            - redis

    # Redis
    redis:
        image: redis:7.0.15-alpine
        hostname: redis
        expose:
            - 6379
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping"]
            interval: 20s
            timeout: 10s
            retries: 5

    # RabbitMQ
    rabbitmq:
        image: rabbitmq:3.13.3-management-alpine
        hostname: rabbitmq3
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - 15672:15672
        expose:
            - 5672
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 20s
            timeout: 10s
            retries: 5

networks:
    default:
        name: bagel
